language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt5-default qt5-qmake qtbase5-dev-tools qtchooser qttools5-dev qtbase5-dev libqt5gui5 libqt5widgets5

install:
  - qmake
  - make
  
script:
# - ./Application

 notifications:
   email:
     - Pierre.Houdayer.Etu@univ-lemans.fr
     - Damien.Guedon.Etu@univ-lemans.fr
   on_success: change
   on_failure: always
